source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.4', '>= 6.1.4.4'
# Use sqlite3 as the database for Active Record
gem 'sqlite3', '~> 1.4'
# Use Puma as the app server
gem 'puma', '~> 5.0'
#
# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

gem 'grpc', "1.42"
gem 'grpc-web', "~> 1.2"

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem "rspec-rails", "~> 5.1"
end


gem "net-smtp", "~> 0.3.1"
gem "net-imap", "~> 0.2.3"
gem "net-pop", "~> 0.1.1"

gem "rack-cors", "~> 1.1"

gem "pry", "~> 0.14.1"

gem "faker", "~> 2.20", :group => :development
